version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  # ジョブの名前（なんでもいいです）
  test-build-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            # テスト
            - run: yarn test
            # ビルド
            - run: yarn build
            # cliからNetlifyにデプロイできるようにするライブラリをインストール
            # - run: yarn add netlify-cli
            # デプロイ（詳細は後述します）
            # - run: yarn netlify deploy -p -d デプロイするディレクトリ名 -a ${Personal access tokensの名前} -s ${API IDの名前}

workflows:
  test-build-deploy:
    jobs:
      # filtersの設定は必須ではありません。
      # filtersを設定しない場合は、pushした際にブランチ問わずCircleCIが稼働します。
      - build-and-test:
          filters:
            branches:
              only: master
