version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  # ジョブの名前（なんでもいいです）
  build-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            # ビルド
            - run: yarn build
            # テスト
            - run: yarn test
            # デプロイ
            - run: echo "deploy start"
            # cliからNetlifyにデプロイできるようにするライブラリをインストール
            # - run: yarn add netlify-cli
            # デプロイ（詳細は後述します）
            # - run: yarn netlify deploy -p -d デプロイするディレクトリ名 -a ${Personal access tokensの名前} -s ${API IDの名前}
  acceptance_test1:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn test

workflows:
  build-deploy:
    jobs:
      # filtersの設定は必須ではありません。
      # filtersを設定しない場合は、pushした際にブランチ問わずCircleCIが稼働します。
      - build-deploy
  
